/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e1982d8a4f4b55911b4d29f
*
* You will get 10% discount for each one of your friends
* 
*/
package com.ccim.db.ccim_db.service.base;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;


import com.ccim.db.ccim_db.entity.CCIM1;

import com.ccim.db.ccim_db.entity.User;

import com.ccim.db.ccim_db.repositories.CCIM1Repository;

@Service
@Transactional
public class CCIM1BaseService {

	
	@Autowired
	CCIM1Repository ccim1Repository;


    // CRUD METHODS
    
	// CRUD - REMOVE
    
	public void delete(Long id) {
		ccim1Repository.delete(id);
	}

    
    // CRUD - FIND BY Wallet

    public List<CCIM1> findByWallet(User user) {
		return ccim1Repository.findByWallet(user);
	}
    
	// CRUD - GET ONE
    	
	public CCIM1 getOne(Long id) {
		return ccim1Repository.findOne(id);
	}

    	
    // CRUD - GET LIST
    	
	public List<CCIM1> getAll() {
		List<CCIM1> list = new ArrayList<>();
		ccim1Repository.findAll().forEach(list::add);
		return list;
	}
	

}
